### ISSUE TITLE
Cannot currently update package

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/smac-feedstock#13]
Due to a non-standard version check (Ref: https://github.com/conda-forge/smac-feedstock/pull/9) it is currently impossible for us to update the package until this is changed upstream.

**Comment by mfeurer** [comment]
Hey @BastianZim is this an issue in conda-forge or SMAC?

**Comment by BastianZim** [comment]
Hi @mfeurer it's a bit of both. Some of the packages in conda-forge don't have a version attached in a way that can be read by `pkg_resources.get_distribution`due to the way conda-forge compiles them. 
Unfortunately, smac is unable to fall back to other ways to read them as outlined in https://github.com/conda-forge/smac-feedstock/pull/9#issuecomment-1044290983 so the import process fails. 
IMHO checking for a version during import is a non-standard thing to do so I'm not sure why smac actually does that.

**Comment by mfeurer** [comment]
We used to get a lot of issues about the dependencies not being installed correctly wrt a package that requires compilation and SWIG (pyrfr), and people using the wrong OS (Windows). To not have these issues during the optimization we decided to fail at import time. @renesass could you please have a look at #9 here?
